### ISSUE TITLE
Improve handling of slow API calls

### ISSUE THREAD

**Issue by raphaelcm** [namely/ruby-client#39]
Some Namely API requests are very slow (like >30s). This means that RestClient will throw a timeout exception before the request completes.

Two ways to resolve:
1. Set RestClient `timeout` param to `-1` (never timeout): http://stackoverflow.com/a/11658655/862544
2. Allow caller to pass in a timeout param to when making API calls via this wrapper

**Comment by raphaelcm** [comment]
In talking with Namely API support, it sounds like adding support for paging through results (rather than retrieving all) would also fix this.

**Comment by bobbytables** [comment]
@raphaelcm This PR addresses this: #40

**Comment by raphaelcm** [comment]
Thanks @bobbytables, when will an updated version of the gem be released?

**Comment by bobbytables** [comment]
@raphaelcm - I will work on getting this out.

**Comment by bobbytables** [comment]
I don't have access so I'll find who does :)

**Comment by raphaelcm** [comment]
Thanks! LMK when a new gem version is cut - our mutual customers are anxious to have this fix in place.

**Comment by bobbytables** [comment]
@raphaelcm - Tagged as v0.2.2

**Comment by raphaelcm** [comment]
@bobbytables v0.2.2 solves the issue. Thanks!
