### ISSUE TITLE
Drop backports / old rubies?

### ISSUE THREAD

**Issue by odlp** [namely/ruby-client#42]
Using Ruby 2.4.0, our Rails app spits out warnings from the `backports` gem, which is required by the `namely` gem:

```
/Users/oli/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/backports-3.6.8/lib/backports/1.8.7/fixnum/div.rb:1: warning: constant ::Fixnum is deprecated
/Users/oli/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/backports-3.6.8/lib/backports/1.8.7/fixnum/fdiv.rb:1: warning: constant ::Fixnum is deprecated
/Users/oli/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/backports-3.6.8/lib/backports/2.1.0/bignum/bit_length.rb:1: warning: constant ::Bignum is deprecated
/Users/oli/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/backports-3.6.8/lib/backports/2.1.0/fixnum/bit_length.rb:1: warning: constant ::Fixnum is deprecated
```

Looking at this repo I noticed the `travis.yml` also uses old version of Ruby:

```
rvm:
  - 1.9.3
  - jruby-19mode
  - 2.0.0
  - 2.1.3
```

Ruby [1.9.3](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/) and [2.0.0](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/) have now reached end-of-life status. Could they be dropped, along with backports?

**Comment by odlp** [comment]
It's worth mentioning that the `namely` gem adds over 400ms to loading the Rails environment on my machine, almost as expensive as Rails:

```
# Durations in ms:
    203.36  neat
    236.46  delayed_job_active_record
    268.24  composite_primary_keys
    413.12  namely
    500.48  rails
```



And digging deeper this is almost entirely due to `backports`:

```
0.2123460000148043 delayed_job
0.25004600000102073 sprockets/railtie
0.26063500001328066 active_record/railtie
0.3938990000169724 backports
0.4654549999977462 rails
```

So there's a nice upside to removing `backports` too.

**Comment by carlosplusplus** [comment]
Thanks for the help with this, @odlp !
