### ISSUE TITLE
Support `per_page` parameter?

### ISSUE THREAD

**Issue by artfuldodger** [namely/ruby-client#44]
We're seeing a lot of 502 responses when attempting to fetch profiles, and it looks like the current recommendation is to fetch 20 per page, while it defaults to 30:

https://developers.namely.com/1.0/profiles/profiles-index

Is this currently supported by the gem? I did not find any reference to `per_page` in the code.

**Comment by RUN-CMD** [comment]
I this Namely client is paginating profiles by default, however it's a bit obscured.

They appear to be using an undocumented `after` parameter in lieu of `page` and `per_page`, [as specified in the documentation](https://developers.namely.com/1.0/profiles/profiles-index).

Here's where they appear to be paginating, in a loop that seems to lean on the `after` parameter and the server's default pagination to terminate once it's captured all profiles:
https://github.com/namely/ruby-client/blob/master/lib/namely/resource_gateway.rb#L52

I would expect to find this `after` parameter in their API documentation, but it's not there. So, I can't say for sure:
https://developers.namely.com/1.0/profiles/profiles-index

Would someone familiar with the Namely API internals be able to comment?

**Comment by ncherro** [comment]
@artfuldodger @RUN-CMD sorry for the very late reply here, but yes:

1. the `after` parameter, which this gem uses, is supported as an undocumented 'legacy pagination' param in our v1 API
2. `per_page` is accepted by our API, and if left blank our API will return 30 records. this gem doesn't specify the `per_page` parameter, so you'll always get 30 records in the response

Per the [Configuration](https://github.com/namely/ruby-client#configuration) section of our readme, it is possible to specify both `http_codes_to_retry` and `retries`. This should get you past intermittent 50x response errors.
