### ISSUE TITLE
504 GatewayTimeout returned while retrieving paged profiles

### ISSUE THREAD

**Issue by rreinhardt9** [namely/ruby-client#47]
While using `connection.profiles.all` occasionally the namely API will return a 504 gateway timeout status while retrieving one of the pages. This raises an exception and derails the (sometimes lengthy) process of retrieving all of the paged results.

One possible solution would be to catch that exception and retry a few times before returning the error. PR example solution forthcoming...

**Comment by rreinhardt9** [comment]
#47 is an example of how I think we might be able to make the gem more resilient to the gateway timeouts that have been occurring.

**Comment by apanzerj** [comment]
The API itself is terribly slow. 

Running benchmark for each page request in the gem I get the following times:

```
8.606905999826267
10.8720350000076
4.774912999942899
6.914371999911964
11.757528000045568
17.46250699996017
5.260852999985218
10.408723999978974
3.9185280001256615
4.31420599995181
```

And then a gateway timeout.
